-- return {
-- 	'akinsho/bufferline.nvim',
-- 	version = "*",
-- 	dependencies = 'nvim-tree/nvim-web-devicons',
--     opts = {
--       options = {
        -- stylua: ignore
        -- close_command = function(n) Snacks.bufdelete(n) end,
        -- stylua: ignore
        -- right_mouse_command = function(n) Snacks.bufdelete(n) end,
--         diagnostics = "nvim_lsp",
--         always_show_bufferline = false,
--         offsets = {
--           {
--             filetype = "neo-tree",
--             text = "Neo-tree",
--             highlight = "Directory",
--             text_align = "left",
--           },
--           {
--             filetype = "snacks_layout_box",
--           },
--         },
--         ---@param opts bufferline.IconFetcherOpts
--         get_element_icon = function(opts)
--           return LazyVim.config.icons.ft[opts.filetype]
--         end,
--       },
--     }
-- }
return {}
